# This is a basic workflow to help you get started with Actions

name: React App Deploy to Surge
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: install NodeJS
      - uses: actions/setup-node@v4-beta
        with: 
          node-version: 18
      
      - uses: borales/actions-yarn@v4.0.0
        with:
           cmd: install 

      - name: Build React App
        run: yarn build

      - name: Install Surge
        run: npm install --global surge
       
      
