name: React App Build and Deploy to Surge
on:
  push:
    branches:
      - master  # or 'main', depending on your setup

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      # Set the correct working directory
      - name: Install dependencies
        run: yarn install
        working-directory: ./project001

      - name: Build React app
        run: yarn build
        working-directory: ./project001

      - name: Install Surge
        run: npm install --global surge

      - name: Deploy to Surge
        run: surge ./build project001.surge.sh --token ${{ secrets.SURGE_TOKEN }}
